name: Publish to PyPI registry

on:
  push:
    branches: [ master ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.0'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry wheel
          poetry config experimental.new-installer false
#      - name: Test with pytest + generate coverage
#        shell: bash
#        run: |
#          poetry run python -m coverage run || exit $?
#          poetry run python -m coverage html -i
#          poetry run python -m coverage report > coverage.txt
#          cat coverage.txt
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v2
#        with:
#          fail_ci_if_error: true
#          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish to PyPI
        shell: bash
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} --build
